services:
  web:
    build: ./web
#    volumes:
#      - ./web/html:/var/www/html # uncomment to update web docs in real time
    ports:
      - "80:80"
  db:
    build: ./db
    environment:
      POSTGRES_PASSWORD: ""
      POSTGRES_HOST_AUTH_METHOD: "trust"
